1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
import numpy as np
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [9]:
import numpy as np
a = np.random.randint(1,11, size=(5,5))
print(a)

[[ 4  5 10  1 10]
 [ 2  4  7  6  9]
 [ 3  3  9  7  9]
 [ 2  7  1  5  6]
 [ 3  7  2  5  5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
import numpy as np
a = np.random.rand(4,4)
print(a)

[[0.81519527 0.24872013 0.7526704  0.76050293]
 [0.57082699 0.49723218 0.65709409 0.00312163]
 [0.11724949 0.62047434 0.38653397 0.17704545]
 [0.37496836 0.63119084 0.95947647 0.96334542]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [31]:
import numpy as np
a = np.random.randint(1,11, size=(5,))
b = np.random.randint(1,11, size=(5,))
print(f"The sum of both is:\n {np.add(a,b)}")

print(f"The substraction is:\n {np.subtract(a,b)}")

print(f"The multiplication is:\n {a * b}")


The sum of both is:
 [ 6  7 10 15  9]
The substraction is:
 [ 0 -5  6  5  7]
The multiplication is:
 [ 9  6 16 50  8]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [30]:
import numpy as np
a = np.random.random(7)
b = np.random.random(7)
dot_ab = np.dot(a,b)
print(f"The scalar product of vectors, a and b, is: \n {dot_ab}")

The scalar product of vectors, a and b, is: 
 1.230550269373032


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [20]:
import numpy as np
A = np.random.randint(1,11, size=(2,2))
B = np.random.randint(1,11, size=(2,3))
mult = np.dot(A, B)
print(f"The multiplication of matrices a and b is:\n {mult}")

The multiplication of matrices a and b is:
 [[68 93 42]
 [60 80 36]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [22]:
import numpy as np
A = np.random.randint(1,11, size=(3,3))
print(A)

a_inv = np.linalg.inv(A)
print(a_inv)

[[10  2 10]
 [ 1  5  6]
 [ 9  8 10]]
[[-0.00763359 -0.22900763  0.14503817]
 [-0.16793893 -0.03816794  0.19083969]
 [ 0.14122137  0.23664122 -0.18320611]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [18]:
import numpy as np
A = np.random.rand(4,4)
print(f"The orginal matrix is: \n {A}")
B = A.T
print(f"The transpose matrix is:\n {B}")

The orginal matrix is: 
 [[0.357521   0.45664836 0.82682214 0.66561716]
 [0.88627589 0.76627067 0.93327487 0.66187528]
 [0.75226687 0.54656867 0.67560127 0.5573801 ]
 [0.32383952 0.10476822 0.44720542 0.71926432]]
The transpose matrix is:
 [[0.357521   0.88627589 0.75226687 0.32383952]
 [0.45664836 0.76627067 0.54656867 0.10476822]
 [0.82682214 0.93327487 0.67560127 0.44720542]
 [0.66561716 0.66187528 0.5573801  0.71926432]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [29]:
import numpy as np
matrix = np.random.randint(1, 11, size=(3,4))
vector = np.random.randint(1, 11, size=4)
result = np.dot(matrix, vector)
print(result)


[102  50 105]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [28]:
import numpy as np
matrix = np.random.random((2,3))
vector = np.random.random(3)
result = np.dot(matrix, vector)
print(result)

[1.27202986 0.50588908]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [27]:
import numpy as np
A = np.random.randint(1,11, size=(2,2))
B = np.random.randint(1,11, size=(2,2))
print(f"Result: \n {A*B}")


Result: 
 [[12 63]
 [21 81]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [26]:
import numpy as np
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1, 11, size=(2,2))
result = np.dot(a,b)
print(f"The product is: \n {result}")

The product is: 
 [[ 32  48]
 [ 58 110]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [25]:
import numpy as np
a = np.random.randint(1, 101, size=(5,5))
print(f"The sum of the elements in the matrix is: {np.sum(a)}")

The sum of the elements in the matrix is: 1224


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [24]:
import numpy as np
a = np.random.randint(1, 11, size=(4,4))
b = np.random.randint(1, 11, size=(4,4))
print(f"The difference between a and b: \n {np.subtract(a,b)}")

The difference between a and b: 
 [[ 1 -2  6  2]
 [ 9  1  3  0]
 [ 0 -9 -3 -7]
 [ 3 -1 -5 -3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [23]:
import numpy as np
A = np.random.rand(3,3)
print(f"Matrix:\n {A}")
row_sum = np.sum(A, axis=1)
vector = np.reshape(row_sum, (3,1))
print(f"Vector row:\n {vector}")

Matrix: 
 [[0.07177338 0.57643249 0.93834611]
 [0.60743185 0.29510259 0.75157226]
 [0.72554024 0.240027   0.27838492]]
Vector row: 
 [[1.58655198]
 [1.65410671]
 [1.24395216]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [22]:
import numpy as np
A = np.random.randint(1,10, size=(3,4))
B = A ** 2
print(f"The squares of the elements in A:\n{B}")

The squares of the elements in A:
[[36 25 25 36]
 [81  1 25  4]
 [81  1 81 81]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [21]:
import numpy as np
a = np.random.randint(1,50, size=4)
print(f"The original vector is:\n{a}")

sqrt_vector = np.sqrt(a)
print(f"The vector of square roots is:\n{sqrt_vector}")

The original vector is:
[ 8 29 26  7]
The vector of square roots is:
[2.82842712 5.38516481 5.09901951 2.64575131]
